// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx2He6B1Jx5YinLjKTi3L39lmJkuTajsc',
    appId: '1:939268047607:web:043ec8bdc7df2b98c5c9f2',
    messagingSenderId: '939268047607',
    projectId: 'alex-da075',
    authDomain: 'alex-da075.firebaseapp.com',
    storageBucket: 'alex-da075.firebasestorage.app',
    measurementId: 'G-LEKHLDMM0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRCX8-R6wNpRlSBxTP5_hu0BVR8LKubA',
    appId: '1:939268047607:android:45499df45aac55d0c5c9f2',
    messagingSenderId: '939268047607',
    projectId: 'alex-da075',
    storageBucket: 'alex-da075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuN0AVBU6XYACzjceJXWguwYSW3Lg1Mks',
    appId: '1:939268047607:ios:92b2736aab6e596ec5c9f2',
    messagingSenderId: '939268047607',
    projectId: 'alex-da075',
    storageBucket: 'alex-da075.firebasestorage.app',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuN0AVBU6XYACzjceJXWguwYSW3Lg1Mks',
    appId: '1:939268047607:ios:92b2736aab6e596ec5c9f2',
    messagingSenderId: '939268047607',
    projectId: 'alex-da075',
    storageBucket: 'alex-da075.firebasestorage.app',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx2He6B1Jx5YinLjKTi3L39lmJkuTajsc',
    appId: '1:939268047607:web:fab0c2ea843389e6c5c9f2',
    messagingSenderId: '939268047607',
    projectId: 'alex-da075',
    authDomain: 'alex-da075.firebaseapp.com',
    storageBucket: 'alex-da075.firebasestorage.app',
    measurementId: 'G-SB1P1K7V2R',
  );
}
